services:
  - name: docker:24.0-dind
    alias: docker

stages:
  - build-jar
  - build-docker
  - deploy

build-to-jar:
  stage: build-jar
  image: maven:latest
  script:
    - mvn clean package -DskipTests
  only:
    - main
    - ci-test
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: build-docker
  image: docker:latest
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main
    - ci-test
  dependencies:
    - build-to-jar

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cat $SSH_PRIVATE_KEY | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  script:
    - ssh -o StrictHostKeyChecking=accept-new $DEPLOY_USER@$DEPLOY_SERVER "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA &&
        docker stop mordappka_web || true &&
        docker rm mordappka_web || true &&
        docker run -d -p 8080:80 --name mordappka_web $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      "
  only:
    - main
    - ci-test
