FROM ghcr.io/graalvm/jdk-community:24
VOLUME /tmp
COPY target/*.jar app.jar
ENV DATABASE_IP=$DB_IP
ENV DATABASE_PASSWD=$DB_PASSWORD
ENV DATABASE_USERNAME=$DB_USERNAME
ENV DATABASE_PORT=$DB_PORT
ENV DATABASE_NAME=$DB_NAME

ENTRYPOINT ["java","-jar","app.jar"]